Repository MaskingTechnology/jitar, pull requests merged in 2022-10, with the labels that each got.

#6 Setup dependabot config
  .github/dependabot.yml
Labels: enhancement

#26 #25: processed feedback.
  website/src/css/layout.css
  website/src/index.html
Labels: website

#22 #21: improved the client id generation and validation
  jitar/src/runtime/ClientId.ts
  jitar/src/runtime/LocalRepository.ts
  jitar/src/server/controllers/ModulesController.ts
  jitar/test/runtime/ClientId.spec.ts
  jitar/test/runtime/LocalRepository.spec.ts
Labels: Security

#28 5 make docs mobile friendly
  documentation/_includes/header.html
  documentation/_layouts/default.html
  documentation/assets/css/site.css
  documentation/assets/libs/responsive.js
Labels: documentation

#29 Added v0.1.1 information
  CHANGELOG.md
  jitar/package.json
Labels: enhancement
